title: "Jan & Izabela" 
email: wesele2k24@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Grodzisk Mazowiecki,
  
  Czerwiec 22, 2024
owner: Jan K
first_published: 2024
# baseurl: "jan-iza-wedding" # the subpath of your site, e.g. /blog
# url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Build settings
markdown: kramdown
